### ISSUE TITLE
How to activate Scooter

### ISSUE THREAD

**Issue by DoidoYo** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#3]
Hello, what are the expected commands to the motor controller? Does it have to be unlocked first to then start sending break and throttle information? Is the password needed? I'm also trying to build a BLE controller replacement. While I'm able to read the information between the stock BLE and motor controller, I'm having trouble activating the motor and running it with my custom one. Any help is appreciated.

**Comment by camcamfresh** [comment]
So I haven't tried enabling the password on the scooter, though I do remember seeing it on the MiHome app. I've tested the break and throttle information and as long as the scooter is on, the BLE controller sends the values, however if the scooter is locked the motor controller will not activate the motor (though it still receives the values). I would avoid using the word activate since the motor controller does need to be activated once to begin working (I'm not sure how this works but some guys in Russia activate the control boards for like $35 I think, if I find the link again I'll tag it on this thread). Now once it the motor control is activated, it will respond to commands sent by the BLE board. It doesn't matter if the motor controller loses power it will stay activated.  When I began experimenting with the communication data I literally copied the exact packets I was monitoring between the factory BLE board and the motor controller and programmed my microchip to send those. As a result, I had to spin the scooter's wheel before turning the microcontroller on (began communicating with the motor controller) but I was able to successfully turn on the motor although it was only at one speed.

**Comment by jacknab** [comment]
hi,
I actually been looking for details on how to make my own BLE board for my scooter, I came across your project here on Github - which totally looks like an exciting project to play around with, I didn't finish reading the description/deals.. I spontaneously went for it.. and without any hesitation purchased the Particle Electron cellular kit.  
*Question now:  does the scooter still need the BLE board?
I have 2 M365 scooters, one is fully functioning, my second scooter I actually found in this very cluttered thrift store, sticker price was $10.00   -  however after much troubleshooting I have discovered the ble controller board was fried.

camcamfresh you mentioned you programmed your own microcrontroller could I ask what type of components you used?  Was it something Arduino like?

**Comment by camcamfresh** [comment]
No it does not need the BLE board. I did purchase a BLE board, but that was strictly for learning about the messages it sends to the scooter's motor controller (that is where I learned about the information request packet structure; it's in the escControl function of firmware.ino).

I completely eliminated the BLE board from the scooter and replaced it with the Particle Electron. It is very similar to Arduino (both use C++ if remember correctly), but it also has cellular capabilities. 

microcontroller = particle electron (I also sometimes use it to describe the motor controller and BMS circuit boards). Not sure if this is the correct terminology, but I've never taken a computer science class about any of this so ... that's what I call it for now.

**Comment by jacknab** [comment]
awsome i have ordered the particle cellular board however the version that
had gps board was sold out, the board arrive tomorrow.

anyway of taking some photos of your project to see its design and wiring.



.

**Comment by jacknab** [comment]
how are u sending commands to the particle board?  i know over celullar but
did u create a simple web page to do this

**Comment by camcamfresh** [comment]
I usually use the Particle IDE, but am working on a swift program using HTML Post method (check the Particle Documentation). I am having trouble completing the program as I do not own a mac.

**Comment by jacknab** [comment]
thanks for the quick response, I see you have also updated your code, just downloaded it - I received my Electron Particle couple hours ago- however its just the Electron it doesn't have gps board, because the site was sold out. As soon as they get them in stock the site will email me and I will purchase it.

I connected the electron to the 4 wires, still need to connect to throttle, light and motor wires.

I tried writing your firmware file to the electron but since I dont have gps its giving me errors, so I am going through and commenting out the gps stuff for the moment.

Arduino: 1.8.7 (Windows 10), Board: "Arduino/Genuino Uno"

sketch_nov07a:1:14: error: expected constructor, destructor, or type conversion before '(' token

 SYSTEM_THREAD(ENABLED);

              ^

C:\Users\chadb\Downloads\Xiaomi-M365-BLE-Controller-Replacement-master (1)\Xiaomi-M365-BLE-Controller-Replacement-master\firmware\sketch_nov07a\sketch_nov07a.ino: In function 'void setup()':

sketch_nov07a:7:5: error: 'Serial1' was not declared in this scope

     Serial1.begin(115200);

     ^

sketch_nov07a:10:5: error: 'Particle' was not declared in this scope

     Particle.function("CloudCommand", cloudCommand);

     ^

sketch_nov07a:19:13: error: 'D0' was not declared in this scope

     pinMode(D0, INPUT);//Power Monitor

             ^

sketch_nov07a:20:13: error: 'D1' was not declared in this scope

     pinMode(D1, OUTPUT);//Power

             ^

sketch_nov07a:21:13: error: 'D2' was not declared in this scope

     pinMode(D2, OUTPUT);//Buzer

             ^

sketch_nov07a:22:13: error: 'D3' was not declared in this scope

     pinMode(D3, OUTPUT);//Red (Lock)

             ^

sketch_nov07a:23:13: error: 'D4' was not declared in this scope

     pinMode(D4, OUTPUT);//Green (Unlock)

             ^

sketch_nov07a:24:13: error: 'D5' was not declared in this scope

     pinMode(D5, OUTPUT);//Blue (Connecting)

             ^

C:\Users\chadb\Downloads\Xiaomi-M365-BLE-Controller-Replacement-master (1)\Xiaomi-M365-BLE-Controller-Replacement-master\firmware\sketch_nov07a\sketch_nov07a.ino: In function 'void escControl()':

sketch_nov07a:68:5: error: 'Serial1' was not declared in this scope

     Serial1.write(motor, sizeof(motor)); delay(10);

     ^

C:\Users\chadb\Downloads\Xiaomi-M365-BLE-Controller-Replacement-master (1)\Xiaomi-M365-BLE-Controller-Replacement-master\firmware\sketch_nov07a\sketch_nov07a.ino: In function 'void escReader()':

sketch_nov07a:136:11: error: 'Serial1' was not declared in this scope

     while(Serial1.available()){

           ^

sketch_nov07a:176:51: error: 'D2' was not declared in this scope

                             if(beep == 0x01) tone(D2, 20, 50);

                                                   ^

sketch_nov07a:177:57: error: 'D2' was not declared in this scope

                             else if(beep == 0x02){ tone(D2, 20, 100); beep = 0x01;}

                                                         ^

sketch_nov07a:178:57: error: 'D2' was not declared in this scope

                             else if(beep == 0x03){ tone(D2, 20, 50); beep = 0x01;}

                                                         ^

sketch_nov07a:192:38: error: 'D2' was not declared in this scope

                                 tone(D2, 20, 5000);

                                      ^

sketch_nov07a:193:33: error: 'Particle' was not declared in this scope

                                 Particle.publish("Alarm", "Alarm Alert!");

                                 ^

C:\Users\chadb\Downloads\Xiaomi-M365-BLE-Controller-Replacement-master (1)\Xiaomi-M365-BLE-Controller-Replacement-master\firmware\sketch_nov07a\sketch_nov07a.ino: In function 'void backgroundProcess()':

sketch_nov07a:213:20: error: 'D0' was not declared in this scope

     if(digitalRead(D0) == LOW){

                    ^

sketch_nov07a:214:22: error: 'D1' was not declared in this scope

         digitalWrite(D1, HIGH);

                      ^

sketch_nov07a:218:25: error: 'Particle' was not declared in this scope

     if(locked == 0x0 && Particle.connected()){

                         ^

sketch_nov07a:219:22: error: 'D3' was not declared in this scope

         digitalWrite(D3, LOW);

                      ^

sketch_nov07a:220:22: error: 'D4' was not declared in this scope

         digitalWrite(D4, HIGH);

                      ^

sketch_nov07a:221:22: error: 'D5' was not declared in this scope

         digitalWrite(D5, LOW);

                      ^

sketch_nov07a:224:22: error: 'D3' was not declared in this scope

         digitalWrite(D3, HIGH);

                      ^

sketch_nov07a:225:22: error: 'D4' was not declared in this scope

         digitalWrite(D4, LOW);

                      ^

sketch_nov07a:226:22: error: 'D5' was not declared in this scope

         digitalWrite(D5, LOW);

                      ^

sketch_nov07a:229:22: error: 'D3' was not declared in this scope

         digitalWrite(D3, LOW);

                      ^

sketch_nov07a:230:22: error: 'D4' was not declared in this scope

         digitalWrite(D4, LOW);

                      ^

sketch_nov07a:231:22: error: 'D5' was not declared in this scope

         digitalWrite(D5, HIGH);

                      ^

sketch_nov07a:234:22: error: 'D3' was not declared in this scope

         digitalWrite(D3, LOW);

                      ^

sketch_nov07a:235:22: error: 'D4' was not declared in this scope

         digitalWrite(D4, LOW);

                      ^

sketch_nov07a:236:22: error: 'D5' was not declared in this scope

         digitalWrite(D5, HIGH);

                      ^

C:\Users\chadb\Downloads\Xiaomi-M365-BLE-Controller-Replacement-master (1)\Xiaomi-M365-BLE-Controller-Replacement-master\firmware\sketch_nov07a\sketch_nov07a.ino: In function 'int cloudCommand(String)':

sketch_nov07a:248:9: error: 'Serial1' was not declared in this scope

         Serial1.write(unlock, sizeof(unlock));

         ^

sketch_nov07a:252:9: error: 'Serial1' was not declared in this scope

         Serial1.write(lock, sizeof(lock));

         ^

sketch_nov07a:256:9: error: 'Serial1' was not declared in this scope

         Serial1.write(tailoff, sizeof(tailoff));

         ^

sketch_nov07a:260:9: error: 'Serial1' was not declared in this scope

         Serial1.write(tailon, sizeof(tailon));

         ^

sketch_nov07a:264:9: error: 'Serial1' was not declared in this scope

         Serial1.write(cruiseoff, sizeof(cruiseoff));

         ^

sketch_nov07a:268:9: error: 'Serial1' was not declared in this scope

         Serial1.write(cruiseon, sizeof(cruiseon));

         ^

sketch_nov07a:272:22: error: 'D1' was not declared in this scope

         digitalWrite(D1, HIGH);

                      ^

sketch_nov07a:278:14: error: 'D2' was not declared in this scope

         tone(D2, 20, 5000);

              ^

exit status 1
expected constructor, destructor, or type conversion before '(' token

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
